-- DROP DATABASE `superrecruiter`;

-- MySQL Script generated by MySQL Workbench
-- Fri Feb 16 12:10:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema superrecruiter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema superrecruiter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `superrecruiter` DEFAULT CHARACTER SET utf8 ;
USE `superrecruiter` ;

-- -----------------------------------------------------
-- Table `superrecruiter`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Role` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superrecruiter`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Person` (
  `user_id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `ssn` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `hired` TINYINT NULL DEFAULT NULL,
  `registration_date` VARCHAR(255) NOT NULL,
  `Role_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_Person_Role1_idx` (`Role_name` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `ssn_UNIQUE` (`ssn` ASC),
  CONSTRAINT `fk_Person_Role1`
    FOREIGN KEY (`Role_name`)
    REFERENCES `superrecruiter`.`Role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superrecruiter`.`Availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Availability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `Person_user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Availability_Person1_idx` (`Person_user_id` ASC),
  CONSTRAINT `fk_Availability_Person1`
    FOREIGN KEY (`Person_user_id`)
    REFERENCES `superrecruiter`.`Person` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superrecruiter`.`Competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Competence` (
  `Name` VARCHAR(255) NOT NULL,
  `name_sv` VARCHAR(255) NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superrecruiter`.`Experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Experience` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `years` DECIMAL NULL,
  `Competence_Name` VARCHAR(255) NOT NULL,
  `Person_user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Experience_Competence1_idx` (`Competence_Name` ASC),
  INDEX `fk_Experience_Person1_idx` (`Person_user_id` ASC),
  CONSTRAINT `fk_Experience_Competence1`
    FOREIGN KEY (`Competence_Name`)
    REFERENCES `superrecruiter`.`Competence` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Experience_Person1`
    FOREIGN KEY (`Person_user_id`)
    REFERENCES `superrecruiter`.`Person` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




-- REPLACE DB CREATION ABOVE THIS
-- ------------------------------------------------------------------------------------------
-- INSERTING SOME NEEDED VALUES

-- ONLY RECRUIT AND APPLICANT NEEDED IN "role"
INSERT INTO role (name) VALUES ("recruit");
INSERT INTO role (name) VALUES ("applicant");


-- POSSIBLE COMPETENCES FOR STARTING WITH:
INSERT INTO competence (name, name_sv)
VALUES ("Sausage BBQ", "Korvgrillning");
INSERT INTO competence (name, name_sv)
VALUES ("Carousel technician", "Karuselldrift");
INSERT INTO competence (name, name_sv)
VALUES ("Cotton candy maker", "Sockervaddande");
INSERT INTO competence (name, name_sv)
VALUES ("Popper", "Poppare");
INSERT INTO competence (name, name_sv)
VALUES ("Ghost", "Spöke");
INSERT INTO competence (name, name_sv)
VALUES ("Sound tech", "Ljudtekniker");
INSERT INTO competence (name, name_sv)
VALUES ("Light tech", "Ljustekniker");
INSERT INTO competence (name, name_sv)
VALUES ("Bingo caller", "Bingoutropare");
INSERT INTO competence (name, name_sv)
VALUES ("Lottery seller", "Lotteriförsäljare");
