-- MySQL Script generated by MySQL Workbench
-- Thu Feb  8 15:03:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema superrecruiter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema superrecruiter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `superrecruiter` DEFAULT CHARACTER SET utf8 ;
USE `superrecruiter` ;

-- -----------------------------------------------------
-- Table `superrecruiter`.`Availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Availability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superrecruiter`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Role` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superrecruiter`.`Competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Competence` (
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superrecruiter`.`Experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Experience` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `years` DECIMAL NULL,
  `Competence_Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Experience_Competence1_idx` (`Competence_Name` ASC),
  CONSTRAINT `fk_Experience_Competence1`
    FOREIGN KEY (`Competence_Name`)
    REFERENCES `superrecruiter`.`Competence` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `superrecruiter`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `superrecruiter`.`Person` (
  `user_id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `ssn` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `hired` TINYINT NULL DEFAULT NULL,
  `registration_date` VARCHAR(255) NOT NULL,
  `Availability_id` INT NOT NULL,
  `Role_name` VARCHAR(255) NOT NULL,
  `Experience_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_Person_Availability_idx` (`Availability_id` ASC),
  INDEX `fk_Person_Role1_idx` (`Role_name` ASC),
  INDEX `fk_Person_Experience1_idx` (`Experience_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `ssn_UNIQUE` (`ssn` ASC),
  CONSTRAINT `fk_Person_Availability`
    FOREIGN KEY (`Availability_id`)
    REFERENCES `superrecruiter`.`Availability` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Role1`
    FOREIGN KEY (`Role_name`)
    REFERENCES `superrecruiter`.`Role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Person_Experience1`
    FOREIGN KEY (`Experience_id`)
    REFERENCES `superrecruiter`.`Experience` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
